[theme]
primaryColor = "#3b82f6"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f9ff"
textColor = "#1e293b"
font = "sans serif"

[server]
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = true
```

---

## 📄 **ARCHIVO 7: `.gitignore`**
```
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
env/
venv/
ENV/
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg
.streamlit/secrets.toml
.vscode/
.idea/
*.swp
*.swo
*~
.DS_Store
Thumbs.db
.pytest_cache/
.coverage
htmlcov/
*.pdf
temp/
uploads/